import json
import logging
import mlflow
import dagshub


# Set up MLflow tracking URI
dagshub.init(
    repo_owner="singhsumitt05",
    repo_name="mlops-mini",
    mlflow=True
)

mlflow.set_tracking_uri(
    "https://dagshub.com/singhsumitt05/mlops-mini.mlflow"
)


# Logging configuration
logger = logging.getLogger("model_registration")
logger.setLevel(logging.DEBUG)

console_handler = logging.StreamHandler()
console_handler.setLevel(logging.DEBUG)

file_handler = logging.FileHandler(
    "model_registration_errors.log"
)
file_handler.setLevel(logging.ERROR)

formatter = logging.Formatter(
    "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)

console_handler.setFormatter(formatter)
file_handler.setFormatter(formatter)

logger.addHandler(console_handler)
logger.addHandler(file_handler)


def load_model_info(file_path: str) -> dict:
    """Load model information from JSON file."""
    try:
        with open(file_path, "r") as file:
            model_info = json.load(file)

        logger.debug(
            "Model info loaded from %s",
            file_path
        )

        return model_info

    except FileNotFoundError:
        logger.error("File not found: %s", file_path)
        raise

    except Exception as e:
        logger.error(
            "Unexpected error occurred while loading model info: %s",
            e
        )
        raise


def register_model(model_name: str, model_info: dict):
    """Register the MLflow logged model."""

    try:
        # Use the model URI generated by MLflow
        model_uri = model_info["model_uri"]

        logger.debug(
            "Registering model using URI: %s",
            model_uri
        )

        # Register the model
        model_version = mlflow.register_model(
            model_uri=model_uri,
            name=model_name
        )

        logger.debug(
            "Model %s version %s registered successfully.",
            model_name,
            model_version.version
        )

        # Transition model to Staging
        client = mlflow.tracking.MlflowClient()

        client.transition_model_version_stage(
            name=model_name,
            version=model_version.version,
            stage="Staging"
        )

        logger.debug(
            "Model %s version %s transitioned to Staging.",
            model_name,
            model_version.version
        )

    except Exception as e:
        logger.error(
            "Error during model registration: %s",
            e
        )
        raise


def main():

    try:
        model_info_path = (
            "reports/experiment_info.json"
        )

        model_info = load_model_info(
            model_info_path
        )

        model_name = "my_model"

        register_model(
            model_name,
            model_info
        )

    except Exception as e:

        logger.error(
            "Failed to complete the model registration process: %s",
            e
        )

        print(f"Error: {e}")


if __name__ == "__main__":
    main()